package com.game.entity;

import java.io.Serializable;

import org.hibernate.validator.constraints.NotBlank;

public class Adminuser implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 8750418493811513026L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adminuser.adminId
     *
     * @mbggenerated Mon Apr 24 18:11:04 CST 2017
     */
    private Integer adminid;
   
    private Roleinfo roleinfo;
    
	public Roleinfo getRoleinfo() {
		return roleinfo;
	}

	public void setRoleinfo(Roleinfo roleinfo) {
		this.roleinfo = roleinfo;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adminuser.roleId
     *
     * @mbggenerated Mon Apr 24 18:11:04 CST 2017
     */
    private Integer roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adminuser.adminName
     *
     * @mbggenerated Mon Apr 24 18:11:04 CST 2017
     */
    @NotBlank(message="员工账户不能为空")
    private String adminname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adminuser.adminPass
     *
     * @mbggenerated Mon Apr 24 18:11:04 CST 2017
     */
    @NotBlank(message="密码不能为空")
    private String adminpass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adminuser.email
     *
     * @mbggenerated Mon Apr 24 18:11:04 CST 2017
     */
    private String email;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adminuser.adminId
     *
     * @return the value of adminuser.adminId
     *
     * @mbggenerated Mon Apr 24 18:11:04 CST 2017
     */
    public Integer getAdminid() {
        return adminid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adminuser.adminId
     *
     * @param adminid the value for adminuser.adminId
     *
     * @mbggenerated Mon Apr 24 18:11:04 CST 2017
     */
    public void setAdminid(Integer adminid) {
        this.adminid = adminid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adminuser.roleId
     *
     * @return the value of adminuser.roleId
     *
     * @mbggenerated Mon Apr 24 18:11:04 CST 2017
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adminuser.roleId
     *
     * @param roleid the value for adminuser.roleId
     *
     * @mbggenerated Mon Apr 24 18:11:04 CST 2017
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adminuser.adminName
     *
     * @return the value of adminuser.adminName
     *
     * @mbggenerated Mon Apr 24 18:11:04 CST 2017
     */
    public String getAdminname() {
        return adminname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adminuser.adminName
     *
     * @param adminname the value for adminuser.adminName
     *
     * @mbggenerated Mon Apr 24 18:11:04 CST 2017
     */
    public void setAdminname(String adminname) {
        this.adminname = adminname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adminuser.adminPass
     *
     * @return the value of adminuser.adminPass
     *
     * @mbggenerated Mon Apr 24 18:11:04 CST 2017
     */
    public String getAdminpass() {
        return adminpass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adminuser.adminPass
     *
     * @param adminpass the value for adminuser.adminPass
     *
     * @mbggenerated Mon Apr 24 18:11:04 CST 2017
     */
    public void setAdminpass(String adminpass) {
        this.adminpass = adminpass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adminuser.email
     *
     * @return the value of adminuser.email
     *
     * @mbggenerated Mon Apr 24 18:11:04 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adminuser.email
     *
     * @param email the value for adminuser.email
     *
     * @mbggenerated Mon Apr 24 18:11:04 CST 2017
     */
    public void setEmail(String email) {
        this.email = email;
    }
}