package com.game.entity;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Table;

@Table(name="functionmenu")
public class Functionmenu implements Serializable{
   
	
	/**
	 * 
	 */
	private static final long serialVersionUID = -2567445984509046984L;

	private boolean checked =false;
	
    public boolean getChecked() {
		return checked;
	}

	public void setChecked(boolean checked) {
		this.checked = checked;
	}
	
    private Integer funid;

    private Set<Functionmenu> resources = new HashSet<Functionmenu>(0);
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column functionmenu.funName
     *
     * @mbggenerated Mon Apr 24 18:11:04 CST 2017
     */
    private String funname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column functionmenu.funUrl
     *
     * @mbggenerated Mon Apr 24 18:11:04 CST 2017
     */
    private String funurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column functionmenu.displayAsMenu
     *
     * @mbggenerated Mon Apr 24 18:11:04 CST 2017
     */
    private Boolean displayasmenu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column functionmenu.parentFunId
     *
     * @mbggenerated Mon Apr 24 18:11:04 CST 2017
     */
    private Integer parentfunid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column functionmenu.funId
     *
     * @return the value of functionmenu.funId
     *
     * @mbggenerated Mon Apr 24 18:11:04 CST 2017
     */
    public Integer getFunid() {
        return funid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column functionmenu.funId
     *
     * @param funid the value for functionmenu.funId
     *
     * @mbggenerated Mon Apr 24 18:11:04 CST 2017
     */
    public void setFunid(Integer funid) {
        this.funid = funid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column functionmenu.funName
     *
     * @return the value of functionmenu.funName
     *
     * @mbggenerated Mon Apr 24 18:11:04 CST 2017
     */
    
    private Functionmenu resource; // 父级
    
    
    
    
    
    
    
    public Functionmenu getResource() {
		return resource;
	}

	public void setResource(Functionmenu resource) {
		this.resource = resource;
	}

	public String getFunname() {
        return funname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column functionmenu.funName
     *
     * @param funname the value for functionmenu.funName
     *
     * @mbggenerated Mon Apr 24 18:11:04 CST 2017
     */
    public void setFunname(String funname) {
        this.funname = funname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column functionmenu.funUrl
     *
     * @return the value of functionmenu.funUrl
     *
     * @mbggenerated Mon Apr 24 18:11:04 CST 2017
     */
    public String getFunurl() {
        return funurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column functionmenu.funUrl
     *
     * @param funurl the value for functionmenu.funUrl
     *
     * @mbggenerated Mon Apr 24 18:11:04 CST 2017
     */
    public void setFunurl(String funurl) {
        this.funurl = funurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column functionmenu.displayAsMenu
     *
     * @return the value of functionmenu.displayAsMenu
     *
     * @mbggenerated Mon Apr 24 18:11:04 CST 2017
     */
    public Boolean getDisplayasmenu() {
        return displayasmenu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column functionmenu.displayAsMenu
     *
     * @param displayasmenu the value for functionmenu.displayAsMenu
     *
     * @mbggenerated Mon Apr 24 18:11:04 CST 2017
     */
    public void setDisplayasmenu(Boolean displayasmenu) {
        this.displayasmenu = displayasmenu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column functionmenu.parentFunId
     *
     * @return the value of functionmenu.parentFunId
     *
     * @mbggenerated Mon Apr 24 18:11:04 CST 2017
     */
    public Integer getParentfunid() {
        return parentfunid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column functionmenu.parentFunId
     *
     * @param parentfunid the value for functionmenu.parentFunId
     *
     * @mbggenerated Mon Apr 24 18:11:04 CST 2017
     */
    public void setParentfunid(Integer parentfunid) {
        this.parentfunid = parentfunid;
    }

	public Set<Functionmenu> getResources() {
		return resources;
	}

	public void setResources(Set<Functionmenu> resources) {
		this.resources = resources;
	}
    
    
}