package com.game.entity;

public class Rolefunmenurel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rolefunmenurel.relId
     *
     * @mbggenerated Mon Apr 24 18:11:04 CST 2017
     */
    private Integer relid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rolefunmenurel.roleId
     *
     * @mbggenerated Mon Apr 24 18:11:04 CST 2017
     */
    private Integer roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rolefunmenurel.funId
     *
     * @mbggenerated Mon Apr 24 18:11:04 CST 2017
     */
    private Integer funid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rolefunmenurel.relId
     *
     * @return the value of rolefunmenurel.relId
     *
     * @mbggenerated Mon Apr 24 18:11:04 CST 2017
     */
    public Integer getRelid() {
        return relid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rolefunmenurel.relId
     *
     * @param relid the value for rolefunmenurel.relId
     *
     * @mbggenerated Mon Apr 24 18:11:04 CST 2017
     */
    public void setRelid(Integer relid) {
        this.relid = relid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rolefunmenurel.roleId
     *
     * @return the value of rolefunmenurel.roleId
     *
     * @mbggenerated Mon Apr 24 18:11:04 CST 2017
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rolefunmenurel.roleId
     *
     * @param roleid the value for rolefunmenurel.roleId
     *
     * @mbggenerated Mon Apr 24 18:11:04 CST 2017
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rolefunmenurel.funId
     *
     * @return the value of rolefunmenurel.funId
     *
     * @mbggenerated Mon Apr 24 18:11:04 CST 2017
     */
    public Integer getFunid() {
        return funid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rolefunmenurel.funId
     *
     * @param funid the value for rolefunmenurel.funId
     *
     * @mbggenerated Mon Apr 24 18:11:04 CST 2017
     */
    public void setFunid(Integer funid) {
        this.funid = funid;
    }
}