package com.game.entity;

public class Roleinfo {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column roleinfo.roleId
	 *
	 * @mbggenerated Mon Apr 24 18:11:04 CST 2017
	 */
	private Integer roleid;
	private Integer adminCount;

	public Integer getAdminCount() {
		return adminCount;
	}

	public void setAdminCount(Integer adminCount) {
		this.adminCount = adminCount;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column roleinfo.roleName
	 *
	 * @mbggenerated Mon Apr 24 18:11:04 CST 2017
	 */
	private String rolename;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column roleinfo.roleDesc
	 *
	 * @mbggenerated Mon Apr 24 18:11:04 CST 2017
	 */
	private String roledesc;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column roleinfo.roleId
	 *
	 * @return the value of roleinfo.roleId
	 *
	 * @mbggenerated Mon Apr 24 18:11:04 CST 2017
	 */
	public Integer getRoleid() {
		return roleid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column roleinfo.roleId
	 *
	 * @param roleid
	 *            the value for roleinfo.roleId
	 *
	 * @mbggenerated Mon Apr 24 18:11:04 CST 2017
	 */
	public void setRoleid(Integer roleid) {
		this.roleid = roleid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column roleinfo.roleName
	 *
	 * @return the value of roleinfo.roleName
	 *
	 * @mbggenerated Mon Apr 24 18:11:04 CST 2017
	 */
	public String getRolename() {
		return rolename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column roleinfo.roleName
	 *
	 * @param rolename
	 *            the value for roleinfo.roleName
	 *
	 * @mbggenerated Mon Apr 24 18:11:04 CST 2017
	 */
	public void setRolename(String rolename) {
		this.rolename = rolename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column roleinfo.roleDesc
	 *
	 * @return the value of roleinfo.roleDesc
	 *
	 * @mbggenerated Mon Apr 24 18:11:04 CST 2017
	 */
	public String getRoledesc() {
		return roledesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column roleinfo.roleDesc
	 *
	 * @param roledesc
	 *            the value for roleinfo.roleDesc
	 *
	 * @mbggenerated Mon Apr 24 18:11:04 CST 2017
	 */
	public void setRoledesc(String roledesc) {
		this.roledesc = roledesc;
	}
}